version: '3.7'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - /usr/src/app/dist

  ci:
    build:
      context: .
      dockerfile: Dockerfile
      target: ci
    ports:
      - '3000:3000'
