apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas
  namespace: baas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baas
  template:
    metadata:
      labels:
        app: baas
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          image: jelkand/baas:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '256Mi'
              cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: baas
  namespace: baas
spec:
  selector:
    app: baas
  ports:
    - port: 3000
      # targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: baas-ingress
  namespace: baas
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: baas
              servicePort: 3000
            path: /sort-integers
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: baas
  namespace: baas
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: baas
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80